services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
    volumes:
      - ./reports:/app/reports
      - ./backend:/app/backend
      - ./application.py:/app/application.py
    env_file:
      - .env