# backend/nodes/researchers/company.py
import logging  # <-- ADDED
from typing import Any, Dict

from langchain_core.messages import AIMessage

from ...classes import ResearchState
from .base import BaseResearcher
from backend.utils.utils import company_name

logger = logging.getLogger(__name__)  # <-- ADDED

class CompanyBriefNode(BaseResearcher):
    def __init__(self) -> None:
        super().__init__()
        # v2: Renamed analyst_type
        self.analyst_type = "company_brief"

    async def analyze(self, state: ResearchState) -> Dict[str, Any]:
        company = company_name(state)
        msg = [f"🏢 Company Brief Node analyzing {company}"]

        # V3: Get queries from state generated by QueryGeneratorNode
        queries = state.get('research_queries', {}).get(self.analyst_type, [])

        # Add message to show subqueries with emojis
        subqueries_msg = "🔍 Subqueries for company brief:\n" + "\n".join([f"• {query}" for query in queries])
        messages = state.get('messages', [])
        messages.append(AIMessage(content=subqueries_msg))
        state['messages'] = messages

        # Send queries through WebSocket
        if websocket_manager := state.get('websocket_manager'):
            if job_id := state.get('job_id'):
                await websocket_manager.send_status_update(
                    job_id=job_id,
                    status="processing",
                    message="Company brief queries generated",
                    result={
                        "step": "Company Brief", # v2: Updated step name
                        "analyst_type": self.analyst_type, # v2: Uses new type
                        "queries": queries
                    }
                )

        company_brief_data = {}

        # If we have site_scrape data, include it first
        if site_scrape := state.get('site_scrape'):
            msg.append(f"\n📊 Including {len(site_scrape)} pages from company website...")
            company_brief_data.update(site_scrape)

        # Perform additional research with comprehensive search
        try:
            # Store documents with their respective queries
            # Perform additional research
            documents_found = await self.search_documents(state)

            if documents_found:
                # Add found documents, associating each with its query
                for url, doc in documents_found.items():
                    doc['query'] = doc.get('query', 'Unknown Query')
                    company_brief_data[url] = doc
                msg.append(f"\n✓ Found {len(documents_found)} documents from web search.")
                logger.info(f"Found {len(documents_found)} documents from web search.")
            else:
                msg.append("\nℹ️ No additional documents found from web search.")
                logger.info("No additional documents found from web search.")

            if websocket_manager := state.get('websocket_manager'):
                if job_id := state.get('job_id'):
                    await websocket_manager.send_status_update(
                        job_id=job_id,
                        status="processing",
                        message=f"Found {len(documents_found)} documents for {self.analyst_type}",
                        result={
                            "step": "Searching",
                            "analyst_type": self.analyst_type,
                            "queries": queries,
                            "documents_found": len(documents_found)
                        }
                    )

        except Exception as e:
            msg.append(f"\n⚠️ Error during research: {str(e)}")
            logger.error(f"Error during company research: {e}")

        # Update state with our findings
        messages = state.get('messages', [])
        messages.append(AIMessage(content="\n".join(msg)))
        state['messages'] = messages

        # v2: Update state with the new key
        state['company_brief_data'] = company_brief_data

        # Return the modified state in-place to preserve pass-through keys
        return state

    async def run(self, state: ResearchState) -> ResearchState:
        """
        Entry point for the LangGraph node execution.
        Calls the analyze method and returns the updated state.
        """
        try:
            await self.analyze(state)
        except Exception as e:
            logger.error(f"CompanyBriefNode run failed: {e}")
            # Ensure key exists even on failure
            if 'company_brief_data' not in state:
                state['company_brief_data'] = {}
        return state  # Always return the state