import logging
from typing import Any, Dict

from langchain_core.messages import AIMessage

from ...classes import ResearchState
from .base import BaseResearcher
from backend.utils.utils import company_name

logger = logging.getLogger(__name__)


class NewsSignalNode(BaseResearcher):
    def __init__(self) -> None:
        super().__init__()
        # v2: Renamed analyst_type for UI/logging
        self.analyst_type = "news_signal" 

    async def analyze(self, state: ResearchState) -> Dict[str, Any]:
        company = company_name(state)
        msg = [f"📰 News Signal Node analyzing {company}"]

        # V3: Get queries from state generated by QueryGeneratorNode
        queries = state.get('research_queries', {}).get(self.analyst_type, [])

        subqueries_msg = "🔍 Subqueries for news & signals:\n" + "\n".join([f"• {query}" for query in queries])
        messages = state.get('messages', [])
        messages.append(AIMessage(content=subqueries_msg))
        state['messages'] = messages

        news_signal_data = {}

        # Include site_scrape data for news analysis
        if site_scrape := state.get('site_scrape'):
            msg.append(f"\n📊 Including {len(site_scrape)} pages from company website...")
            news_signal_data.update(site_scrape)

        # Perform additional research
        try:
            # Store documents with their respective queries
            documents_found = await self.search_documents(state)
            if documents_found:  # Only process if we got results
                for url, doc in documents_found.items():
                    doc['query'] = doc.get('query', 'Unknown Query') # Associate each document
                    news_signal_data[url] = doc

            msg.append(f"\n✓ Found {len(news_signal_data)} documents")
            if websocket_manager := state.get('websocket_manager'):
                if job_id := state.get('job_id'):
                    await websocket_manager.send_status_update(
                        job_id=job_id,
                        status="processing",
                        message=f"Used Tavily Search to find {len(news_signal_data)} documents",
                        result={
                            "step": "Searching",
                            "analyst_type": self.analyst_type, # v2: Uses new type
                            "queries": queries
                        }
                    )
        except Exception as e:
            msg.append(f"\n⚠️ Error during research: {str(e)}")

        # Update state with our findings
        messages = state.get('messages', [])
        messages.append(AIMessage(content="\n".join(msg)))

        # v2: Update state with the new key
        state['news_signal_data'] = news_signal_data

        # Return the modified state in-place to preserve pass-through keys
        return state

    async def run(self, state: ResearchState) -> ResearchState:
        """
        Entry point for the LangGraph node execution.
        Calls the analyze method and returns the updated state.
        """
        try:
            await self.analyze(state)
        except Exception as e:
             logger.error(f"NewsSignalNode run failed: {e}")
             state.setdefault('messages', []).append(AIMessage(content=f"News node failed: {e}"))
             state.setdefault('news_signal_data', {})
        
        # Modify state in-place and return the full state to preserve pass-through keys
        return state